[bug] Harmonize dialog boxes across the application
openmrs/openmrs-owa-obsadmin pull request #35
Opened 2017-09-22 14:12 UTC by andela-cuchendu

# JIRA TICKET NAME:
PDMO-30: [Harmonize dialog boxes across the application](https://issues.openmrs.org/browse/PDMO-30)

## SUMMARY:
Harmonize dialog boxes across the application

2017-09-22 14:21 UTC, andela-jomadoye commented
Good job @andela-cuchendu

2017-09-22 14:42 UTC, kingisaac95 commented
For code readability, you may want to consider changing the indentations of the buttons.
Instead of having this:
```
<button
    type="button" className="btn btn-danger form-control cancelBtn"
    data-dismiss="modal"
>
   Close
</button>
```
you can indent it to look like this:
```
<button
    type="button"
    className="btn btn-danger form-control cancelBtn"
    data-dismiss="modal"
>Close</button>
```
so that the text to be displayed on the button can be seen clearly without confusing it for a prop.

Apart from that, the work looks good to me. Good job @andela-cuchendu 👍

2017-09-23 11:54 UTC, jacksono requested changes

2017-09-23 11:54 UTC, jacksono commented on app/js/components/subAddress/addressForm.jsx
> +                </div>
Seems theres a typo on the prompt message. "Are you sure **you** want to delete this address?

2017-09-23 11:54 UTC, jacksono commented on app/js/components/obs.jsx
>                </div>
Seems theres a typo on the prompt message. "Are you sure **you** want to delete this Observation?

2017-09-23 11:55 UTC, jacksono commented
Good job 👍

2017-09-25 09:25 UTC, andela-cuchendu commented
All done. Thank you  @jacksono and @kingisaac95

2017-09-25 12:37 UTC, merged